version: 1
formatters:
  detailed:
    format: '%(asctime)s %(levelname)s [%(filename)s:%(lineno)d] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: detailed
    level: INFO
    stream: ext://sys.stdout
loggers:
  myapp:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]
